### ISSUE TITLE
Request: Change "nation" to "country"

### ISSUE THREAD

**Issue by kappelmann** [lukasstevens/scrape-mep-mails#2]
As far as I understand the difference (https://english.stackexchange.com/questions/15007/state-vs-country-as-nation), a nation might not have sovereignty when contrasted to a country/state.
Country is also used in the frontend and currently mapping back to "nation". See https://github.com/kappelmann/mep_contact_frontend/blob/master/src/consts/sqls.ts#L22

On a related note, is there a good way to share the schema definitions between the two repositories in some way? E.g. save the SQL schema as a JSON?

**Comment by lukasstevens** [comment]
First part fixed in 463ca3d. Second part fixed in 0d25d50.
